<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12.0</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CtfDeck.Contracts\CtfDeck.Contracts.csproj" />
        <ProjectReference Include="..\CtfDeck.Abstractions\CtfDeck.Abstractions.csproj" />
        <ProjectReference Include="..\CtfDeck.Data\CtfDeck.Data.csproj"/>
        <EmbeddedResource Include="Resources\tool-catalog.json" />
    </ItemGroup>

</Project>
